-- DDL: CREATE TABLE statements for Oracle
CREATE TABLE HR_EMP_INOUT_DETAIL (
    HR_ATT_LOG_ID NUMBER(16,0) NOT NULL,
    EMPLOYEE_ID NUMBER(16,0),
    SWAP_TIME DATE NOT NULL,
    SHIFT VARCHAR2(20),
    ATTENDANCE_DATE DATE,
    MARKED VARCHAR2(20),
    CANCELLED VARCHAR2(1) DEFAULT 'N' NOT NULL,
    IP_ADDRESS VARCHAR2(15),
    PROCESSED VARCHAR2(1) DEFAULT 'N' NOT NULL,
    EMPLOYEE_NO VARCHAR2(10),
    MANUAL_ATTENDANCE VARCHAR2(1) DEFAULT 'N',
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT HR_ATT_LOG_PK PRIMARY KEY (HR_ATT_LOG_ID)
);

CREATE SEQUENCE HR_EMP_INOUT_ID_S START WITH 1 INCREMENT BY 1;
